version: '3.1'


volumes:
    elasticsearch-data:
        driver: local

services:
    nginx:
        image: nginx
        container_name: nginx_jahednia
        volumes:
            - ./nginx_jahednia.conf:/etc/nginx/nginx.conf
        ports:
            - "51125:8080"
        networks:
            hbd-demo-network:
                aliases:
                      - jahednia_stack_nginx
        depends_on:
            elasticsearch:
                condition: service_started
            frontend:
                condition: service_started
            backend:
                condition: service_started

    elasticsearch:
        image: elasticsearch:7.9.2
        container_name: hbd-demo-elasticsearch_clinical_jahednia
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data,
        environment:
            - discovery.type=single-node
        deploy:
            resources:
                limits:
                    memory: 5G
        restart: always
        healthcheck:
            test:
              [
                  "CMD-SHELL",
                  "curl --silent --fail localhost:9200/_cluster/health || exit 1"
              ]
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
            hbd-demo-network:
                aliases:
                      - jahednia_stack_elasticsearch
    frontend:
        image: hbd-demo-frontend:latest
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        volumes:
            - ./frontend/:/usr/src/app/
        # npm install
        container_name: hbd-demo-frontend_jahednia
        restart: always
        command: sh -c "npm install && npm audit fix --force && quasar dev"
        networks:
            hbd-demo-network:
                aliases:
                    - jahednia_stack_frontend
    backend:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        image: hbd-demo-backend:latest
        container_name: hbd-demo-backend_jahednia
        volumes:
            - ./backend/:/workspace/
            - ~/models/:/models/
        environment:
            - PYTHONUNBUFFERED=1
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always
        deploy:
            resources:
                limits:
                    memory: 20GB
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: [ "0" ]
                          capabilities: [ gpu ]
        networks:
            hbd-demo-network:
                aliases:
                    - jahednia_stack_backend


networks:
    hbd-demo-network:
        external: true